# Generated by Django 4.0.2 on 2022-02-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users_who_like',
        ),
        migrations.CreateModel(
            name='Granted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_wishes_likes', models.ManyToManyField(related_name='liked_granted_wishes', to='belt_app.User')),
                ('users_granted_wishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_wishes', to='belt_app.user')),
            ],
        ),
    ]
