# Generated by Django 4.0.2 on 2022-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_remove_wish_users_who_like_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
