# Generated by Django 4.0.2 on 2022-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_alter_wish_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='desc',
            field=models.TextField(default='go'),
            preserve_default=False,
        ),
    ]
