# Generated by Django 4.0.2 on 2022-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_alter_wish_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
